name: daily-zt-to-feishu

on:
  schedule:
    # 这里计划在 每周一到周五 08:30 UTC 触发 = 台湾/北京时间 16:30（盘后） 若要改时间可调整 cron
    - cron: '30 8 * * 1-5'
  workflow_dispatch:  # 支持手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install akshare pandas requests

      - name: Run script (fetch & push)
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          # app_token 和 table_id 可以直接放这里，也可以放到 Secrets（推荐）
          FEISHU_APP_TOKEN: JsWqbseLxaktydsnElVcIGCCnLf
          FEISHU_TABLE_ID: tbljZZCk6C97kLkW
        run: |
          python main.py
